### PR TITLE
Clarify crawling and zulip notifications.

### PR DESCRIPTION
**Pull request by punchagan**
Minor clarifications to about page and add_blog page.

### CODE REVIEW

**Comment by gonzalo-bulnes** [comment]
The clarifications seem really useful to me. I would suggest adding a link to the project `README` pointing to that page for _help_, _troubleshooting_ or _FAQ_.

**Comment by sursh** [comment]
:heart: :shipit:

**Comment by sursh** [comment]
For this paragraph: 

"If you published more than 2 posts between two crawls of the
+                bot, Zulip notifications will be sent only for the latest
+                couple of posts."

What do you think about the slightly tweaked wording?

"If Blaggregator finds many new posts on your blog, it will only post the two most recent posts to Zulip. All of your posts will still be available on blaggregator.us"

**Comment by punchagan** [comment]
Looks good to me! 

I'm traveling tonight. If you get to it before I do, please go ahead and make the change!

**Comment by sursh** [comment]
I should have some time tomorrow! :)

**Comment by punchagan** [comment]
I made the FAQ change as discussed above and merged.

**Comment by punchagan** [comment]
Deployed on production. :shipit:

**Pull request merged**
