### PR TITLE
Add our own file based logging.

### PR DESCRIPTION
**Pull request by punchagan**
This commit adds a file logger that can help us debug some of the issues.  

I'm not sure if heroku deploys mess with any files that are not from the source repo, etc., though. Do they?

### CODE REVIEW

**Comment by sursh** [comment]
Yayyy! Thanks for putting this together. 

Where does this output end up?

**Comment by punchagan** [comment]
The current logs are in `blaggregator.log` and the log file is archived by date at midnight.

**Comment by punchagan** [comment]
Done. The log file gets saved in the blaggregator directory (where manage.py lives).

**Comment by sursh** [comment]
Ah. So that's not going to work with the way Heroku does filesystems.
There's no "disk" to write to that's persistent in the way we're used to
thinking about it. They call it an "ephemeral" filesystem. "Each dyno gets
its own ephemeral filesystem, with a fresh copy of the most recently
deployed code. During the dyno’s lifetime its running processes can use the
filesystem as a temporary scratchpad, but no files that are written are
visible to processes in any other dyno and any files written will be
discarded the moment the dyno is stopped or restarted. For example, this
occurs any time a dyno is replaced due to application deployment and
approximately once a day as part of normal dyno management."

I think the solution is to get a Heroku plugin that stores the logs
somewhere persistent. Or write them to S3.

On Thu, Oct 29, 2015 at 9:44 PM, Puneeth Chaganti <notifications@github.com>
wrote:

> Done. The log file gets saved in the blaggregator directory (where
> manage.py lives).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sursh/blaggregator/pull/102#issuecomment-152378866>.
>



-- 
-Sasha

**Comment by punchagan** [comment]
Yes, I had suspected that, but wasn't sure. Thanks for the detailed explanation! :smile:

**Comment by punchagan** [comment]
I played around a little bit with writing logs to S3, and I think it may be easier to just use one of the Heroku plugins.  I feel it won't be trivial to get an S3 logging handler working correctly, under all conditions.  Or it may just be that I don't have enough time to spend on this! :stuck_out_tongue: 

Closing the PR, since this code is more or less useless.

**Pull request closed without merging**
