### PR TITLE
throttle by number of new posts per crawl, instead of date

### PR DESCRIPTION
**Pull request by nnja**
In regards to issue #56 

I don't think this comment, made [here](https://github.com/sursh/blaggregator/blob/c8017f50f28a0d2b4bae088b0b0e1327870664c3/home/management/commands/crawlposts.py#L68-L72) is correct:

```
# Only post to zulip if the post was created recently
# so that new accounts don't spam zulip with their entire post list
```
Because based on [this](https://github.com/sursh/blaggregator/blob/c8017f50f28a0d2b4bae088b0b0e1327870664c3/home/views.py#L99-L106) method that's run in the view when a new blog is added, it appears that all crawled posts are added to the database, then [skipped over](https://github.com/sursh/blaggregator/blob/c8017f50f28a0d2b4bae088b0b0e1327870664c3/home/management/commands/crawlposts.py#L66) because they already exist. Because of this, none of the existing blog posts at time of creation get announced in Zulip.

Based on this, my proposed fix to the published date/crawled date problem is this:

Since after blog addition by a user, all existing blog posts are saved and ignored, we can assume that any blog post without a database equivalent is a new blog post, regardless of the date.

So, instead of throttling posts by date (< 2 days) we can throttle by amount of posts per author per crawl (in my code it's 2 or less). 

Let me know what you think.

- Nina

### CODE REVIEW

**Comment by nnja** [comment]
@sursh Did you happen to take a look at this?

**Comment by sursh** [comment]
Hi @nnja! thanks for taking a look and this and sorry for the delay at looking it over. 

I believe that in the examples you're giving, you're conflating the date attached to a blog and the date attached to an individual post, so I don't believe that the posts from a newly added blog would automatically be skipped over. The date for each post is the date as parsed from the page. No?

Either way, your method of throttling makes a lot more sense and sidesteps this whole issue! Nice work.

**Comment by sursh** [comment]
Deployed! I have no good way of testing this pre-deploy, so let's keep an eye on Zulip for any weirdness or complaints.

**Comment by sursh** [comment]
One downside of this approach is that the order of the posts on blaggregator.us (by date that the draft is created) doesn't match the order in which they're posted to Zulip (by date that they are published). But only a small fraction of the traffic actually clicks around on blaggregator.us anyhow.

**Comment by punchagan** [comment]
Another bug-let is when I delete my blog from blaggregator, and add it back, the last couple of posts get posted back. We could leave deleted posts around, even when a blog is deleted, to work around this issue. And posts which have already been announced on Zulip won't be announced again.  Thoughts?

**Comment by sursh** [comment]
Ah, because all posts get deleted when you delete their blog, yes?

That approach would fix that problem. One downside is that there is no mechanism to delete their blog *posts* because right now the only way to do that is to delete their *blog*. If there were some such mechanism (maybe a similar interface to the one that lets you delete your blog) I think this would be the best approach, and the most intuitive—it doesn't really make UX sense that 'removing your blog' would also 'delete all previously crawled posts'.

This would also need to play nice with the crawler. What happens when a 'deleted' post gets crawled? Perhaps the UI/UX that would make more sense is to 'hide' posts and 'stop checking' blogs. That way, it's clear that a hidden post won't be re-crawled, and the blog will no longer be checked for updates.

**Pull request merged**
