### PR TITLE
Check for both title and url before creating a post.

### PR DESCRIPTION
**Pull request by punchagan**
This will avoid duplicate posts in the cases when there are minor
changes in the URL, for example -- date changes in the url, change of
unimportant query parameters used for analytics, etc.

### CODE REVIEW

**Comment by punchagan** [comment]
I've played around with this locally, and it seems to fix the issue we see with Medium's posts.

**Comment by sursh** [comment]
This is throwing so many MultipleObjectsReturned now that it's making the logs pretty unreadable. Made an issue #93 to make sure this is resolved after all the deploys (which I will do this weekend)

**Comment by sursh** [comment]
By the way the fact that it's throwing so many of these means that this method is a really good design change :+1:. There are a lot of duplicated posts because of blogs moved, etc.

**Comment by punchagan** [comment]
This is my bad.  The code assumes that the db is "clean" -- does not have duplicate posts.  But, this is not the case on the deployed db.  I'll send a patch sometime later today, to fix this.

**Pull request merged**
